version: "3.9"

services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=Demo
      - HIDE_FOLDERS=docs,private,trash
      - LINE_BREAKS=true
      - ABSOLUTE_PATHES=false
      - ALLOWED_FILE_LINK_TYPES=pdf,mp4
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=true
      - SHOW_LOCAL_GRAPH=true
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      - SITE_TITLE=Demo
      - SITE_TYPE=article
      - SITE_URL=
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=
      - SITE_TWITTER=
      - SITE_LOGO=
      - SITE_HOMEPAGE=
      - SITE_GITHUB=
    volumes:
      - ./perlite/Demo:/var/www/perlite/Demo:ro

  web:
    build:
        context: ./web
    image: sec77/perlite_web:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 80:80
    volumes_from: 
      - perlite       
    depends_on:
      - perlite

